GET http://localhost:8080/quiz
Accept: application/json

###

GET http://localhost:8080/quiz/2
Accept: application/json

###

POST http://localhost:8080/quiz
Accept: application/json
Content-Type: application/json

{
  "name": "Historia polski",
  "questions": [
    {
      "description": "Pierwszym królem polski był...",
      "answers": [
        {
          "value": "Tadeusz Kościuszko",
          "correct": false
        },
        {
          "value": "Jan Paweł ||",
          "correct": false
        },
        {
          "value": "Mieszko |",
          "correct": true
        }
      ]
    },
    {
      "description": "Pierwsza wojna światowa rozpoczęła się w...",
      "answers": [
        {
          "value": "1890 r.",
          "correct": false
        },
        {
          "value": "1914 r.",
          "correct": false
        },
        {
          "value": "1939 r.",
          "correct": true
        }
      ]
    },
    {
      "description": "W skład tak zwanych aliantów wchodziły kraje takie jak...",
      "answers": [
        {
          "value": "Wielka Brytania oraz Francja",
          "correct": true
        },
        {
          "value": "Wenezuela i Indie",
          "correct": false
        },
        {
          "value": "Stany Zjednoczone i Japonia",
          "correct": false
        }
      ]
    }
  ]
}

###


